name: Microservices Build docker hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # Construccion de jars
      - name: Build Micro Articulo
        run: mvn -f MicroserviceArticulo/pom.xml clean install -DskipTests=true
      
      - name: Build Micro Worker
        run: mvn -f MicroserviceWorker/pom.xml clean install -DskipTests=true

      - name: Build Micro Externals
        run: mvn -f MicroserviceExternals/pom.xml clean install -DskipTests=true

      - name: Build Micro Eureka
        run: mvn -f MicroserviceEureka/pom.xml clean install -DskipTests=true


      # Construccion de imagenes
      - name: Build image Articulo
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes1:articulo .
        working-directory: MicroserviceArticulo
        
      - name: Build image Externals
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes1:externals .
        working-directory: MicroserviceExternals
        
      - name: Build image Eureka
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes1:eureka .
        working-directory: MicroServiceEureka

      - name: Build image Worker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mes1:worker .
        working-directory: MicroserviceWorker


      #Login docker
      - name: Log in to Docker Hub 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        
      #Envio de imagenes a docker hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mes1:client
          docker push ${{ secrets.DOCKER_USERNAME }}/mes1:config
          docker push ${{ secrets.DOCKER_USERNAME }}/mes1:eureka
          docker push ${{ secrets.DOCKER_USERNAME }}/mes1:item
